### PR TITLE
Replace custom `np` implementation with direct usage

### LINKED ISSUE #41: Publish passes even though NPM rejects with 24 hour warning
Hi 👋 

I've been trying pika/pack out today for a small util, it's really useful and would love to see it thrive. I found a few little issues I'd like to report, I'll add issues separately. 

This one might be an edge case, but after publishing a lot to try and fix another issue, the versions incremented drastically so I unpublished them all, however on the subsequent publish, the CLI indicates everything was fine and returns the unpkg URL, however yarn actually failed to publish because NPM had blocked publishes for the next 24 hours.

### LINKED ISSUE #44: Suggestion: use branch name as prerelease tag
When creating a pre-release, `next` is suggested to use as the npm tag. I think adding the current git branch name to the list of suggestions would be worthwhile.

Also, requiring `--any-branch` on pre-releases seems unnecessary. Pre-releases are usually done from a branch, as `master` is supposed to be in line with the `latest` tag.

### LINKED ISSUE #48: [Suggestion] Bump version after successful build of package
Right now the third step is to bump the version and the fourth step is to build the package. But when pack fails to build the package, you are stuck with an already tagged commit in the branch and you have to revert a lot of stuff.
It would be easier to fix errors inside the package building process if you wouldn't have to revert the commited tag all the time.

### LINKED ISSUE #51: [publish] Keep lock files in cleanup.
[np](https://github.com/sindresorhus/np)  not removes `lock` files and removes `node_modules` only when there are no any of these files:

https://github.com/sindresorhus/np/blob/64a73f618c07042436d50f8747821c2b6b0d2cca/source/index.js#L110-L137

But `pika-pack publish` removes everything, which can lead to different kind of troubles.

https://github.com/pikapkg/pack/blob/ef6d8fd0295983ab9249021d35de0d0cfa9867c3/src/commands/publish.ts#L113-L125

I would happy to add `np` adaptation in PR.

### PR DESCRIPTION
**Pull request by FredKSchott**
resolves #51, resolves #48, resolves #44, resolves #41, resolves #20 

---

Originally, @pika/pack forked the popular https://github.com/sindresorhus/np package so that it could support its own custom publish pipeline. Forking was chosen over using the package directly so that we would have complete control of the implementation & interface while working around some limitations in the library (specifically: always assuming the `pkg/` sub-directory to be published, and needing to run build after a version bump).

Fast forward to today, and many of the reported issues with this library are related to our custom np fork/implementation. Meanwhile, the np package has continued to improve, fix bugs and add features.

This PR revisits this decision to fork np, and instead calls out to the library directly. This removes ~1000 lines of code from our package, adds new features & bug fixes, and greatly shrinks the complexity of what we need to maintain. 

We now address the original issues as follows:
1. Always pass `--contents pkg/` by default to `np`
2. Require that you have a "version" lifecycle hook/script in your package.json, so that a new build is triggered after every version bump.

While requiring a version script is annoying, it's a worthwhile tradeoff that also allows for users to bring their own publish pipeline/tools if they don't want to use `@pika/pack publish`.

### CODE REVIEW

**Comment by FredKSchott** [comment]
You can try this out today via `npm install @pika/pack@next` or `npx @pika/pack@next build|publish`

**Comment by gr2m** [comment]
Could you point me to the thinking behind making `np` part of the library instead of documenting how to publish using `np` after building with `pack build`? I’m just curious. I don’t use `np` myself as I automate releases with semantic-release, so I’d rather prefer to have it removed altogether. At first sight, publishing seems to be out of scope for a package building tool? Also I just love minimal tools that do one thing well, I’m very biased that way :)

**Comment by tunnckoCore** [comment]
I agree with @gr2m. Let's focus on the building/packaging only.

**Comment by FredKSchott** [comment]
So those two points under "We now address the original issues as follows" are still valid:
1. `npm publish` publishes the top-level directory, and not `pkg/`. Users who don't know how the command works (I would guess most people) will need to go out and figure out how to fix this to publish.
2. We need to build after version bumping (so that `package.json` version -> `pkg/package.json` version). How to do this is also not obvious and can lead to some weirdness.

If you have other ideas on how to address those two issues, I'm definitely interested. This PR was actually an attempt to move closer to what you're describing, where we just wrap a recommended tool with good defaults/options instead of trying to build it ourselves. Let's see how this goes and we could always move to wrapping `npx np` so that theres only a cost when you run it.

**Comment by ghengeveld** [comment]
How about using `np` as an optionalDependency? If it exists, use it, if it doesn't, don't deal with publishing at all. 

I'm a big fan of what pika/pack is offering to solve (the multi env build part), but the publish part just doesn't fit in. I've never had problems using npm version & publish directly. However I have been struggling to incorporate pack into a monorepo Lerna + Yarn workspaces setup over the past weeks. Having multiple tools trying to "solve" the publish part is not helping.

In case you're interested, the wip on that is here: https://github.com/ghengeveld/react-async/pull/44

**Comment by gr2m** [comment]
I would suggest to create a separate package, e.g. `@pika/publish`, which addresses both your points

**Comment by FredKSchott** [comment]
@ghengeveld awesome, will check out react-async.

`@pika/publish` would be interesting, as long as it's easy for a beginner to use and we've communicated well that `npm publish` isn't enough to publish their package. I'd probably still want an `npx @pika/publish` shortcut in that case :)

**Comment by FredKSchott** [comment]
The other thing that this conversation is circling is: are these really just different commands on a single `pika` interface. So instead of `npx @pika/{web|pack|publish}`, is this really just `pika {web|build|publish}`?

**Comment by ghengeveld** [comment]
Honestly, `pack` isn't the best name for a package. I always have to refer to it as "pika pack" which doesn't feel right. I'd be fine with `pika` as the package name, with `pack` being one of its commands.

**Comment by tunnckoCore** [comment]
@FredKSchott, I was thinking about that ever. Move the "runner" implementation to `@pika/runner` or `@pika/core` and make another `@pika/cli` for the cli which will include all of the others as commands.

_IMO, I still think `pack` is too much source code than needed, for actually basic resolving and merging of shareable plugins/configs/etc. :smile:  But anyway._

**Pull request merged**
