### PR TITLE
allow to read pack.config.js file, update CONTRIBUTING.md and package.json

### PR DESCRIPTION
**Pull request by NicoCevallos**
This PR has the following changes
- Allow reading pack.config.js as is requested by https://github.com/pikapkg/pack/issues/45
- Move `@pika/pack` configuration in `package.json` to `pack.config.json`
- Update `checkpoint` folder with the latest code
- Update `CONTRIBUTING.md` adding the steps for Development

### CODE REVIEW

**Comment by FredKSchott** [comment]
Thanks for the contribution! Following up in #51

**Comment by NicoCevallos** [comment]
Sorry, why is it related to #51?

**Comment by rafamel** [comment]
It would be great if this could get some traction!

**Comment by tunnckoCore** [comment]
👎 for moving entirely to a `*.config.js` file. :)

**Comment by NicoCevallos** [comment]
@tunnckoCore why?

**Comment by ryaninvents** [comment]
If I understand correctly, the `@pika/pack` key in package.json is still supported, right? This just gives users another option, plus opens the door for shareable configs

**Comment by NicoCevallos** [comment]
@ryaninvents Yes! that's the idea!
I was working in a project with a set of own libraries and was a bit of pain to update the pipeline for all libs, with this kind of solution I could use a shareable pipeline config, as you said.

**Comment by tunnckoCore** [comment]
Cool. :)

 Yup, that's why I put the word "entirely", meant to say that I'm not agree to be only js file.

Next thing is to move to something like `cosmiconfig` (i have better solution but anyway)

**Comment by layershifter** [comment]
@FredKSchott can you please check this PR? 🙏 We need this feature to reuse same config inside monorepo

**Comment by FredKSchott** [comment]
Hey y;all

This PRs gone out of date a bit, which is my bad for letting it sit this long. Recently we moved all of our projects into a single CLI, and I'd like us to do something similar for configuration. Basically, let's support a single `pika.json`/`pika.config.js` for all Pika projects. 

Follow up conversation here: https://github.com/pikapkg/cli/issues/2

**Pull request closed without merging**
